In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

csv_data = pd.read_csv("https://dqlab-dataset.s3-ap-southeast-1.amazonaws.com/shopping_data.csv")
array = csv_data.values

X = array[:,2:5] #memisahkan fitur dari dataset. 
Y = array[:,0:1]  #memisahkan class dari dataset

dataset=pd.DataFrame({'Customer ID':array[:,0],'Gender':array[:,1],'Age':array[:,2],'Income':array[:,3],'Spending Score':array[:,4]})
print("dataset sebelum dinormalisasi :")
print(dataset.head(10))

min_max_scaler = preprocessing.MinMaxScaler(feature_range=(0,1)) #inisialisasi normalisasi MinMax
data = min_max_scaler.fit_transform(X) #transformasi MinMax untuk fitur
dataset = pd.DataFrame({'Age':data[:,0],'Income':data[:,1],'Spending Score':data[:,2],'Customer ID':array[:,0],'Gender':array[:,1]})

print("dataset setelah dinormalisasi :")
print(dataset.head(10))

dataset sebelum dinormalisasi :
  Customer ID  Gender Age Income Spending Score
0           1    Male  19     15             39
1           2    Male  21     15             81
2           3  Female  20     16              6
3           4  Female  23     16             77
4           5  Female  31     17             40
5           6  Female  22     17             76
6           7  Female  35     18              6
7           8  Female  23     18             94
8           9    Male  64     19              3
9          10  Female  30     19             72
dataset setelah dinormalisasi :
        Age    Income  Spending Score Customer ID  Gender
0  0.019231  0.000000        0.387755           1    Male
1  0.057692  0.000000        0.816327           2    Male
2  0.038462  0.008197        0.051020           3  Female
3  0.096154  0.008197        0.775510           4  Female
4  0.250000  0.016393        0.397959           5  Female
5  0.076923  0.016393        0.765306           6  Female
6 

In [2]:

X = array[:,2:5] #memisahkan fitur dari dataset. 
Y = array[:,0:1]  #memisahkan class dari dataset

print(X)

[[19 15 39]
 [21 15 81]
 [20 16 6]
 [23 16 77]
 [31 17 40]
 [22 17 76]
 [35 18 6]
 [23 18 94]
 [64 19 3]
 [30 19 72]
 [67 19 14]
 [35 19 99]
 [58 20 15]
 [24 20 77]
 [37 20 13]
 [22 20 79]
 [35 21 35]
 [20 21 66]
 [52 23 29]
 [35 23 98]
 [35 24 35]
 [25 24 73]
 [46 25 5]
 [31 25 73]
 [54 28 14]
 [29 28 82]
 [45 28 32]
 [35 28 61]
 [40 29 31]
 [23 29 87]
 [60 30 4]
 [21 30 73]
 [53 33 4]
 [18 33 92]
 [49 33 14]
 [21 33 81]
 [42 34 17]
 [30 34 73]
 [36 37 26]
 [20 37 75]
 [65 38 35]
 [24 38 92]
 [48 39 36]
 [31 39 61]
 [49 39 28]
 [24 39 65]
 [50 40 55]
 [27 40 47]
 [29 40 42]
 [31 40 42]
 [49 42 52]
 [33 42 60]
 [31 43 54]
 [59 43 60]
 [50 43 45]
 [47 43 41]
 [51 44 50]
 [69 44 46]
 [27 46 51]
 [53 46 46]
 [70 46 56]
 [19 46 55]
 [67 47 52]
 [54 47 59]
 [63 48 51]
 [18 48 59]
 [43 48 50]
 [68 48 48]
 [19 48 59]
 [32 48 47]
 [70 49 55]
 [47 49 42]
 [60 50 49]
 [60 50 56]
 [59 54 47]
 [26 54 54]
 [45 54 53]
 [40 54 48]
 [23 54 52]
 [49 54 42]
 [57 54 51]
 [38 54 55]
 [67 54 41]
 [46 54 44